entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  internal:
    address: ":8080"



http:
  routers:
    grafana:
      entryPoints:
        - "internal"
      rule: "PathPrefix(`/grafana`)"
      service: "grafana"