services:
  alert-manager:
    image: prom/alertmanager
    restart: unless-stopped
    volumes:
      - "./alertmanager.yml:/alertmanager/alertmanager.yml"
    networks:
      - localprom
    ports:
      - "9093:9093"
