services:
  alert-manager:
    container_name: alert-manager
    image: docker.io/prom/alertmanager
    user: '1000'
    restart: unless-stopped
    volumes:
      - "../config/alertmanager:/alertmanager"
    ports:
      - "9093:9093"
