services:
  traefik:
    image: traefik:v3.3
    restart: unless-stopped
    command: 
      - --providers.docker
      - --configFile=/config/traefik.yml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config:/config
