services:
  traefik:
    image: traefik:v3.3
    command: 
      - --api.insecure=true 
      - --providers.docker
      - --configFile=/config/traefik.yml
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../conifg:/config
